// Auto-generated by update-assets.js
// Do NOT edit manually. Run: node update-assets.js
window.clientsData = [
  {
    "src": "Assests/Clients/A-build Egypt.png",
    "title": "A-build Egypt"
  },
  {
    "src": "Assests/Clients/AMOC.png",
    "title": "AMOC"
  },
  {
    "src": "Assests/Clients/Anrpc.png",
    "title": "Anrpc"
  },
  {
    "src": "Assests/Clients/EgyptAnode.png",
    "title": "EgyptAnode"
  },
  {
    "src": "Assests/Clients/Egyptian Petrochemicals Company.png",
    "title": "Egyptian Petrochemicals Company"
  },
  {
    "src": "Assests/Clients/egyptian propylene & polypropylene.png",
    "title": "egyptian propylene & polypropylene"
  },
  {
    "src": "Assests/Clients/El Nasr Mining.png",
    "title": "El Nasr Mining"
  },
  {
    "src": "Assests/Clients/Ethydco.png",
    "title": "Ethydco"
  },
  {
    "src": "Assests/Clients/Ezz-Steel.png",
    "title": "Ezz-Steel"
  },
  {
    "src": "Assests/Clients/Hassan Allam.png",
    "title": "Hassan Allam"
  },
  {
    "src": "Assests/Clients/Midor.png",
    "title": "Midor"
  },
  {
    "src": "Assests/Clients/Mist Phosphate.png",
    "title": "Mist Phosphate"
  },
  {
    "src": "Assests/Clients/Petromaint.png",
    "title": "Petromaint"
  },
  {
    "src": "Assests/Clients/Xervon.png",
    "title": "Xervon"
  }
];
