// Auto-generated by update-portfolio.js
// Do NOT edit manually. Run: node update-portfolio.js
window.portfolioData = [
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.33 PM.jpeg",
    "title": "Project 1"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.35 PM (1).jpeg",
    "title": "Project 2"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.35 PM (2).jpeg",
    "title": "Project 3"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.35 PM (3).jpeg",
    "title": "Project 4"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.35 PM (4).jpeg",
    "title": "Project 5"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.35 PM.jpeg",
    "title": "Project 6"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.36 PM (1).jpeg",
    "title": "Project 7"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.39 PM (2).jpeg",
    "title": "Project 8"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.39 PM (3).jpeg",
    "title": "Project 9"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.39 PM (4).jpeg",
    "title": "Project 10"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.39 PM (5).jpeg",
    "title": "Project 11"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.39 PM.jpeg",
    "title": "Project 12"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.40 PM (1).jpeg",
    "title": "Project 13"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.40 PM (3).jpeg",
    "title": "Project 14"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.41 PM (2).jpeg",
    "title": "Project 15"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.41 PM (3).jpeg",
    "title": "Project 16"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.41 PM (5).jpeg",
    "title": "Project 17"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.41 PM (6).jpeg",
    "title": "Project 18"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.42 PM (1).jpeg",
    "title": "Project 19"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.42 PM (2).jpeg",
    "title": "Project 20"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.42 PM (3).jpeg",
    "title": "Project 21"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.42 PM (4).jpeg",
    "title": "Project 22"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.42 PM.jpeg",
    "title": "Project 23"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.43 PM (1).jpeg",
    "title": "Project 24"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.43 PM (2).jpeg",
    "title": "Project 25"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.43 PM (3).jpeg",
    "title": "Project 26"
  },
  {
    "src": "Assests/Portfolio/WhatsApp Image 2024-08-11 at 3.00.43 PM.jpeg",
    "title": "Project 27"
  }
];
